deployment/deploy.sh
deployment/parameters-template.sh

*Description of changes:* Enclose variable in quotes to support whitespace in Identity Center group names. Without this, the command fails when there is a space in the group name.

fix: Support whitespace in group names

---

amplify/backend/function/teamgetIdCGroups/src/index.py

the current code has a bug that only returns the first page of sso groups. The proposed implementation returns all groups, tested on our environment.

Fix retrieval of all groups in the lambda function teamgetIdCGroups-main

---

amplify/backend/tags.json
deployment/deploy.sh
deployment/destroy.sh
deployment/parameters-template.sh
deployment/template.yml
deployment/update.sh
docs/docs/deployment/deployment_process.md
parameters.js

We have to put certain tags (like project, stage, repository, ...) on every CF stack we deploy (and it propagates to (most) resources). 
Example of `parameters.sh` where we define the `TAGS`.
```
...
TEAM_ACCOUNT_PROFILE=test-team
TEAM_ADMIN_GROUP="xxx"
TEAM_AUDITOR_GROUP="yyy"
TAGS="project=iam-identity-center-team stage=prod repository=https://bitbucket.org/stuff other=test"
```
The updated bash scripts are maybe not the cleanest way to achieve this, but it helps me to clarify my use case.
It makes it possible to tag the CF stack for Amplify + all underlying nested stacks.
Tags can also be updated.
We can't hardcode the values in the `tags.json` because we have a stage tag: prod vs non-prod (in a test organization). We try to use a separate params.sh file for …

Make it possible to add custom tags to CF (nested) stacks and underlying resources.

---

amplify/backend/function/teamStatus/teamStatus-cloudformation-template.json
amplify/backend/function/teamgetLogs/teamgetLogs-cloudformation-template.json
amplify/backend/function/teamqueryLogs/teamqueryLogs-cloudformation-template.json

*Issue #, if available:* #50
As per announcement of AWS:
> We are ending support for Node.js 14 in AWS Lambda. This follows Node.js 14 End-Of-Life (EOL) reached on April 30, 2023 [1].
>
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 27, 2023, Lambda will no longer apply security patches and other updates to the Node.js 14 runtime used by Lambda functions, and functions using Node.js 14 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 14 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Node.js 14 runtime.
>
> We recommend that …

refactor: nodejs14.x to nodejs18.x

---

deployment/template.yml

Allow that `CloudTrailAuditLogs` can be empty. 
If you don't define `CLOUDTRAIL_AUDIT_LOGS` in `parameters.sh`, then it will deploy/update your solution using an empty value for that parameter:
```
aws cloudformation deploy ... --parameter-overrides ... CloudTrailAuditLogs= ...
```
Next the condition `IsEmptyCloudTrailAuditLogs` in our `template.yml` will be true. When the condition is true, we will pass the default value `read_write` to our Amplify branch.
```
AmplifyBranch:
Type: AWS::Amplify::Branch
Properties:
...
EnvironmentVariables: 
- ...
- Name: CLOUDTRAIL_AUDIT_LOGS
Value: !If
- IsEmptyCloudTrailAuditLogs
- "read_write"
- !Ref CloudTrailAuditLogs
```

Fix backwards compatibility

---

amplify/backend/function/teamRouter/src/index.py

N/A
ticketNo is not currently being passed as part of the request data and subsequently is not referenced in any Slack Notifications. The value is always, "No ticket provided". This fix simply adds the ticketNo to the request data.
**Currently looks like the following:**
**After code changes:** 

Fix: ticketNo not being referenced in Slack Notifications

---

amplify/backend/api/team/schema.graphql
deployment/api-machine-auth.sh
docs/docs/deployment/configuration/cognito_machine_auth.md

Closes: #33 
This PR implements the following:
1. A script to automate the creation of the needed resources to enable machine authentication on the Cognito User pool: 
- Resource Server with a custom scope of `admin`
- User Pool Client with client secret generation enabled along with the other needed items for machine auth flows and assigned the `api/admin` custom scope.
2. Adds and `auth` rule on each mutation which currently allows full access to members of the `admin` group that grants the same level of access to machine authentication which uses the `api/admin` custom scope. 
I have tested these in or TEAM test environment and validated that I am able to perform the following:
1. Use the client_id and client_secret to obtain a token …

Feature: Enable Machine Authentication to access Graph API Mutations

---

deployment/get-machine-auth-credentials.sh
docs/docs/deployment/configuration/cognito_machine_auth.md

This PR adds two things:
1. The `get-machine-auth-credentials.sh` script. This script automates retrieving the credentials and endpoints needed for utilizing the graphql endpoint programatically.
3. Documentation on how to use the newly added script and reference to the newly published terraform provider. 

Docs: Add terraform provider documentation reference and script for retrieving machine auth credentials

---

amplify/backend/function/teamRouter/custom-policies.json
amplify/backend/function/teamRouter/src/index.py
amplify/backend/function/teamgetGroups/custom-policies.json
amplify/backend/function/teamgetGroups/src/index.py

*Issue #, if available:* #150
From [ListUsers](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html)
> Filtering for a User by the UserName attribute is deprecated. Instead, use the GetUserId API action.
Now need to use [GetUserId](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetUserId.html)
4 occurrences in code: [search: list_users](https://github.com/search?q=repo%3Aaws-samples%2Fiam-identity-center-team%20list_users&type=code)
- teamRouter: used twice, one needs updating. Add GetUserId permission
- teamGetUsers: used once, not with filter, no update needed
- teamGetGroups: used once, swap and replace ListUser permission with GetUserId
By submitting this pull request, I confirm that you …

fix: replace deprecated list_users by username filter with get_user_id

---

amplify/backend/api/team/schema.graphql

*Description of changes:* 
Small change to allow graphql read/update to IAM principals. This allows for integration of TEAM AppSync API with Eventbridge.
Models impacted:
- Eligibility
- Approvers

Update GraphQL schema to allow IAM auth for eligibility and approvers

---

deployment/template.yml

Bump amplify CLI Version
Issue 156
Bumps Amplify CLI to later version which uses node18 for the cognito auth lambdas.
This shouldn't impact existing deployments of the auth lambdas.

Deprecated lambda runtimes #156

---

amplify/backend/custom/cloudtrailLake/cloudtrailLake-cloudformation-template.json
deployment/template.yml
docs/docs/deployment/deployment_process.md

*Description of changes:* Adding in support for passing an existing Cloudtrail Lake EventDataStore to TEAM by extending the use of the CloudTrailAuditLogs parameter to accept an ARN.

FEATURE: Support for existing CloudTrail Lake EDS

---

amplify/backend/api/team/resolvers/Mutation.createRequests.init.1.req.vtl
amplify/backend/api/team/resolvers/Mutation.updateRequests.init.1.req.vtl
src/components/Approvals/Approvals.js
src/components/Requests/Request.js
src/components/Sessions/Active.js

resolve https://github.com/aws-samples/iam-identity-center-team/issues/163
I changed regexp for validation of comment and justification to support unicode characters. 
So, users should be able to use Japanese and some other Asian languages.
I tested my regexp with some samples, please check if this is appropriate behavior.
<details><summary>Backend (click to open) </summary>
<p>
```
$util.matches("[\p{IsAlphabetic}\p{Digit}]", "A") ## upper     -> true
$util.matches("[\p{IsAlphabetic}\p{Digit}]", "a") ## lower     -> true
$util.matches("[\p{IsAlphabetic}\p{Digit}]", "1") ## number    -> true
$util.matches("[\p{IsAlphabetic}\p{Digit}]", "あ") ## Japanese -> true
$util.matches("[\p{IsAlphabetic}\p{Digit}]", "아") ## Korean   -> true …
```

feature: support unicode for comment and justification

---

amplify/backend/function/teamgetMgmtAccountDetails/teamgetMgmtAccountDetails-cloudformation-template.json

Correct invalid Lambda runtime from `3.9` to `python3.9`

Fix lambda runtime from 3.9 to python3.9

---

deployment/parameters-template.sh

The parameter UI_DOMAIN is enabled by default in the parameters.sh. If the default value is left unchanged the installation fails.

fix: comment optional UI_DOMAIN variable

---

amplify/backend/custom/s3bucketSecurity/s3bucketSecurity-cloudformation-template.json
amplify/backend/function/teamListGroups/teamListGroups-cloudformation-template.json
amplify/backend/function/teamNotifications/teamNotifications-cloudformation-template.json
amplify/backend/function/teamRouter/teamRouter-cloudformation-template.json
amplify/backend/function/teamStatus/teamStatus-cloudformation-template.json
amplify/backend/function/teamgetAccounts/teamgetAccounts-cloudformation-template.json
amplify/backend/function/teamgetEntitlement/teamgetEntitlement-cloudformation-template.json
amplify/backend/function/teamgetGroups/teamgetGroups-cloudformation-template.json
amplify/backend/function/teamgetIdCGroups/teamgetIdCGroups-cloudformation-template.json
amplify/backend/function/teamgetLogs/teamgetLogs-cloudformation-template.json
amplify/backend/function/teamgetMgmtAccountDetails/teamgetMgmtAccountDetails-cloudformation-template.json
amplify/backend/function/teamgetOU/teamgetOU-cloudformation-template.json
amplify/backend/function/teamgetOUs/teamgetOUs-cloudformation-template.json
amplify/backend/function/teamgetPermissions/teamgetPermissions-cloudformation-template.json
amplify/backend/function/teamgetUserPolicy/teamgetUserPolicy-cloudformation-template.json
amplify/backend/function/teamgetUsers/teamgetUsers-cloudformation-template.json
amplify/backend/function/teamqueryLogs/teamqueryLogs-cloudformation-template.json
deployment/template.yml

A PR for  Cost/Performance improvements. All the Lambda's run with "simple Python" so not sure if there is a reason why these Lambda's are not running on Graviton.

Update all Lambda's to Graviton

---

amplify/backend/function/teamNotifications/src/index.py

*[Issue 200](https://github.com/aws-samples/iam-identity-center-team/issues/200)*
This PR initialized the `ses` client to the region where the given SES instance is running. This is extracted from the ARN ([stolen the code from here](https://gist.github.com/gene1wood/5299969edc4ef21d8efcfea52158dd40), without optimizing/simplifying it. Maybe it can be reused later on. But in theory it can be stripped to the bare "get region").

Support SES running in a different region

---

amplify/backend/function/teamRouter/src/index.py
src/components/Requests/Request.js

This change fixes an issue where approval for a request would be required, even if an eligibility exists for the account/role being requested that _didn't_ require approval. Take the following two eligibilities:
- RO-Pre-Approved. Eligible to request RO permission set without approval required.
- Admin-Approval-Required: Eligible to request AdministratorAccess and RO access, approval is required. (RO is included in this eligibility as we'd like someone who is a member of this group (and not necessarily a member of the first group!) to be able to access the RO role if it would be more suitable for the task they are performing. More generally, all of our eligibilities are named after the _most permissive_ role it gives access to, but they …

Bypass approval if eligibility not requiring approval exists

---

amplify/backend/function/teamRouter/src/index.py
src/components/Requests/Request.js

#253
This change allows approvers of both an Account and the parent OU to approve a request.
Previously the logic meant that if at least one approver group existed for an account then we'd immediately return that and not consider approvers of the parent OU. Now we build a list of both the accounts approvers groups and the OU approver groups.
I've also changed the error handling slightly, removing the try catch block in `get_approver_group_ids`, as the two functions we call (`get_ou` and `list_approvers` already catch and log a `ClientError` exception, so it's not possible for this exception to bubble up into `get_approver_group_ids`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Allow approval from both account an OU approvers

---

amplify/backend/function/teamNotifications/src/index.py

https://github.com/aws-samples/iam-identity-center-team/issues/263
This simply adds approvers to the slack recipients, and tweaks the wording of the slack message to accommodate.
Note: I haven't tested this as I do not have a test TEAM environment to deploy it into.
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

Send approval/rejection notifications to approvers

---

amplify/backend/function/teamNotifications/src/index.py
docs/docs/deployment/update.md

Updated documentation for new release

Update Documentation for new release

---

package-lock.json

Reverts aws-samples/iam-identity-center-team#339

Revert "Bump nanoid from 3.3.7 to 3.3.8"

---

amplify/backend/custom/stepfunctions/stepfunctions-cloudformation-template.json

*Issue #, if available: #256*
Similar to PR https://github.com/aws-samples/iam-identity-center-team/pull/346, add retry mechanism to account assignment to prevent failure due to throttling. The mentioned issue is already closed, however the issue still remains. 

Add retry mechanism to GrantStateMachine to handle assignment failures

---

amplify/backend/api/team/schema.graphql

Fix issue with a user being able to revoke their own session. Added 'update' permissions to owners for the 'revokerId' field.

fix: User revoke own session

---

README.md
docs/docs/deployment/configuration/cognito_machine_auth.md
docs/docs/deployment/configuration/terraform.md

N/A
The community maintained provider has been moved to a new GitHub organization. This PR intends to update the links for the provider and help make the provider more discoverable. (Existing link still works, as Github performs needed redirects).
This pull requests includes the following:
1. Moves the documentation for the Terraform Provider to its own docs page.
2. Updates the URL for the Provider Registry as the provider has been moved to a new GitHub Organization. 
3. Adds a Quick Link to the community-supported Terraform Provider  to improve visability.

Docs: Update Terraform Provider link and Improve documentation visibility

---

docs/docs/deployment/update.md

N/A
Minor change to documentation to clarify that the update.sh script deploys a cloudformation template, as this was not made clear in the previous documentation

Clarify update process documentation with CloudFormation deployment step

---

amplify/backend/api/team/schema.graphql
amplify/backend/function/teamNotifications/src/index.py
src/components/Admin/Settings.js
src/graphql/queries.js
src/models/index.d.ts
src/models/index.js
src/models/schema.js

This simple change allows the administrator to (optionally) configure a Slack channel to send notifications about activity in the TEAM app, notably:
* Requests
* Approvals
* Rejections

Slack Audit Notifications optional channel

---

amplify/backend/function/team06dbb7fcPreTokenGeneration/Pipfile
amplify/backend/function/teamGetPermissionSets/Pipfile
amplify/backend/function/teamListGroups/Pipfile
amplify/backend/function/teamNotifications/Pipfile
amplify/backend/function/teamPublishOUs/Pipfile
amplify/backend/function/teamRouter/Pipfile
amplify/backend/function/teamgetEntitlement/Pipfile
amplify/backend/function/teamgetMgmtAccountDetails/Pipfile
amplify/backend/function/teamgetUserPolicy/Pipfile

https://github.com/aws-samples/iam-identity-center-team/issues/393
The builds are failing in amplify due to missing dependencies, these changing allowed the build to deploy successfully.

fix: missing dependencies in pipfiles causing build failures

---

amplify/backend/function/teamNotifications/src/index.py

The SNS Publish API has a character limit of 100 for the subject field. If an account name is at it's maximum length of 50 characters, the SNS subject for certain alerts exeeds the 100 character limit resulting in an error. I have shortened each subject string to prevent this error from occuring due to long account names.

Fix SNS subject length

---

amplify/backend/custom/s3bucketSecurity/s3bucketSecurity-cloudformation-template.json
amplify/backend/function/teamGetPermissionSets/Pipfile
amplify/backend/function/teamGetPermissionSets/teamGetPermissionSets-cloudformation-template.json
amplify/backend/function/teamListGroups/Pipfile
amplify/backend/function/teamListGroups/Pipfile.lock
amplify/backend/function/teamListGroups/teamListGroups-cloudformation-template.json
amplify/backend/function/teamNotifications/Pipfile
amplify/backend/function/teamNotifications/Pipfile.lock
amplify/backend/function/teamPublishOUs/Pipfile
amplify/backend/function/teamPublishOUs/teamPublishOUs-cloudformation-template.json
amplify/backend/function/teamRouter/Pipfile
amplify/backend/function/teamRouter/Pipfile.lock
amplify/backend/function/teamRouter/teamRouter-cloudformation-template.json
amplify/backend/function/teamapplicationboto3layer/lib/python/Pipfile
amplify/backend/function/teamapplicationboto3layer/lib/python/Pipfile.lock
amplify/backend/function/teamapplicationboto3layer/parameters.json
amplify/backend/function/teamgetAccounts/teamgetAccounts-cloudformation-template.json
amplify/backend/function/teamgetEntitlement/Pipfile
amplify/backend/function/teamgetEntitlement/teamgetEntitlement-cloudformation-template.json
amplify/backend/function/teamgetIdCGroups/teamgetIdCGroups-cloudformation-template.json
amplify/backend/function/teamgetMgmtAccountDetails/Pipfile
amplify/backend/function/teamgetMgmtAccountDetails/Pipfile.lock
amplify/backend/function/teamgetMgmtAccountDetails/teamgetMgmtAccountDetails-cloudformation-template.json
amplify/backend/function/teamgetOU/teamgetOU-cloudformation-template.json
amplify/backend/function/teamgetOUs/teamgetOUs-cloudformation-template.json
amplify/backend/function/teamgetPermissions/teamgetPermissions-cloudformation-template.json
amplify/backend/function/teamgetUserPolicy/Pipfile
amplify/backend/function/teamgetUserPolicy/teamgetUserPolicy-cloudformation-template.json
amplify/backend/function/teamgetUsers/teamgetUsers-cloudformation-template.json
deployment/template.yml

*Issue #, if available:* N.A.
*Description of changes:* Address urllib3 security vulnerabilities:
1. CVE-2023-43804
2. CVE-2023-45803
3. CVE-2024-37891
By upgrading to Python 3.10, boto3 install urllib3 v2.3.0, which no longer contains vulnerabilities - https://github.com/boto/boto3/blob/99b65dbcbba372f72b9a6b0ac94f5775d40b30b8/requirements-docs.txt#L6.
In addition, [Lambda will soon be deprecating Python 3.9 runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported). This PR upgrades Python runtime to 3.10.

chore: address python security vulnerabilities

---

amplify/backend/function/teamStatus/teamStatus-cloudformation-template.json
amplify/backend/function/teamgetLogs/src/package.json
amplify/backend/function/teamgetLogs/src/yarn.lock
amplify/backend/function/teamgetLogs/teamgetLogs-cloudformation-template.json
amplify/backend/function/teamqueryLogs/src/package.json
amplify/backend/function/teamqueryLogs/src/yarn.lock
amplify/backend/function/teamqueryLogs/teamqueryLogs-cloudformation-template.json
deployment/template.yml

*Issue #, if available:* N.A.
*Description of changes:* Address security vulnerability [CVE-2024-41818](https://github.com/advisories/GHSA-mpg4-rc92-vx8v) from _fast-xml-parser_:
1. _fast-xml-parser_ is a dependency of _@aws-sdk/client-cloudtrail_
2. Updating _@aws-sdk/client-cloudtrail_ updates _fast-xml-parser_ to v4.4.1, which no longer contains the vulnerability
3. Latest _@aws-sdk/client-cloudtrail_ requires node.js 18
4. To use node.js 18 in the Amplify build, we need to update the Build image to _amplify:al2023_
5. Updating the build image to _amplify:al2023_ requires changing how pipenv is installed and made available
In addition, [Lambda will soon be deprecating Node.js 18 runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported). This PR …

chore: address node.js security vulnerabilities
